version: "3"

services:
  server:
    container_name: hacker-news-feed-app
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - database
    volumes:
      - .:/usr/src/hn-feed-app
  database:
    container_name: app-mongodb
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none